/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TRIGGER IF EXISTS `BEFUPD_position`;
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `BEFUPD_position` BEFORE UPDATE ON `position` FOR EACH ROW BEGIN

DECLARE default_department INT(11);

IF NEW.DivisionId IS NULL THEN
	
	SELECT d.RowID FROM `division` d WHERE d.OrganizationID=NEW.OrganizationID ORDER BY d.Created LIMIT 1 INTO default_department;

	IF default_department IS NULL THEN
		INSERT INTO `division`
		(
			Name
			,OrganizationID
			,CreatedBy
			,Created
		) VALUES (
			'Division One'
			,NEW.OrganizationID
			,NEW.CreatedBy
			,CURRENT_TIMESTAMP()
		) ON
		DUPLICATE
		KEY
		UPDATE
			LastUpd=CURRENT_TIMESTAMP()
			,LastUpdBy=NEW.CreatedBy;
			SELECT @@Identity INTO default_department;
	END IF;

	SET NEW.DivisionId = default_department;
	
END IF;

END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
