/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP FUNCTION IF EXISTS `COUNTTHEWEEKS`;
DELIMITER //
CREATE DEFINER=`root`@`localhost` FUNCTION `COUNTTHEWEEKS`(`paramDate` DATE) RETURNS int(11)
    DETERMINISTIC
BEGIN

DECLARE returnvalue INT(11);

DECLARE daythisdate INT(11);



DECLARE one_mon INT(11);

DECLARE one_fri INT(11);

DECLARE count_week INT(11);

DECLARE indx INT(11);

DECLARE lastday INT(11);

DECLARE loop_date DATE;



SET count_week = DAYOFYEAR(DATE_FORMAT(paramDate,'%Y-%m-01')) / 7;

SET returnvalue = DAYOFYEAR(LAST_DAY(paramDate)) / 7;

SET count_week = returnvalue - count_week;

RETURN count_week;

END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
