/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP VIEW IF EXISTS `generator_16`;
DROP TABLE IF EXISTS `generator_16`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `generator_16` AS SELECT 0 `n` UNION SELECT 1 `n` UNION SELECT 2 `n` UNION SELECT 3 `n` UNION SELECT 4 `n` UNION SELECT 5 `n` UNION SELECT 6 `n` UNION SELECT 7 `n` UNION SELECT 8 `n` UNION SELECT 9 `n` UNION SELECT 10 `n` UNION SELECT 11 `n` UNION SELECT 12 `n` UNION SELECT 13 `n` UNION SELECT 14 `n` UNION SELECT 15 `n` UNION SELECT 16 `n` ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
