/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP PROCEDURE IF EXISTS `GetEmployeeTimeEntries`;
DELIMITER //
CREATE PROCEDURE `GetEmployeeTimeEntries`(
	IN `orgId` INT,
	IN `dateFrom` DATE,
	IN `dateTo` DATE
)
BEGIN

DECLARE employeeTypes TEXT;

SELECT
GROUP_CONCAT(l.DisplayValue) `Result`
FROM listofval l
WHERE l.`Type`='RestdayAbsentPolicy'
INTO employeeTypes
;

DROP TEMPORARY TABLE IF EXISTS `timeentries`;
CREATE TEMPORARY TABLE IF NOT EXISTS `timeentries`
SELECT
et.*
FROM employeetimeentry et
INNER JOIN employee e ON e.RowID=et.EmployeeID AND e.OrganizationID=et.OrganizationID AND FIND_IN_SET(e.EmployeeType, employeeTypes) > 0
AND e.EmploymentStatus NOT IN ('Probationary')
WHERE et.OrganizationID=orgId
AND et.`Date` BETWEEN dateFrom AND dateTo
;

END//
DELIMITER ;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
