/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP EVENT IF EXISTS `GROW_dates`;
DELIMITER //
CREATE DEFINER=`root`@`localhost` EVENT `GROW_dates` ON SCHEDULE EVERY 1 DAY STARTS '2017-06-19 16:08:41' ON COMPLETION PRESERVE ENABLE DO BEGIN

DECLARE max_date DATE;

SELECT MAX(d.DateValue)
FROM dates d
INTO max_date;

INSERT INTO dates(DateValue)
VALUES (ADDDATE(max_date, INTERVAL 1 DAY));

END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
