/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP FUNCTION IF EXISTS `IFNEGATIVE`;
DELIMITER //
CREATE FUNCTION `IFNEGATIVE`(`scrutinizeValue` DECIMAL(11,6),
	`fallBackValue` DECIMAL(11,6)
) RETURNS decimal(11,6)
    DETERMINISTIC
BEGIN

DECLARE returnValue DECIMAL(11,6);

IF scrutinizeValue < 0 THEN
	SET returnValue = fallBackValue;
ELSE
	SET returnValue = scrutinizeValue;
END IF;

RETURN returnValue;

END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
