/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP FUNCTION IF EXISTS `INSUPD_employeeshiftbyday`;
DELIMITER //
CREATE FUNCTION `INSUPD_employeeshiftbyday`(`OrganizID` INT, `UserRowID` INT, `EmployeeRowID` INT, `ShiftRowID` INT, `NameOfTheDay` VARCHAR(50), `IsNightShift` CHAR(1), `IsRestDay` CHAR(1), `ByOrderValue` INT, `AsNewRecord` CHAR(1)) RETURNS int(11)
    DETERMINISTIC
BEGIN

DECLARE returnvalue INT(11);
	
RETURN returnvalue;

END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
