/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP VIEW IF EXISTS `leavetimeentry`;
DROP TABLE IF EXISTS `leavetimeentry`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `leavetimeentry` AS select `et`.`RowID` AS `RowID`,`et`.`OrganizationID` AS `OrganizationID`,`et`.`Created` AS `Created`,`et`.`CreatedBy` AS `CreatedBy`,`et`.`LastUpd` AS `LastUpd`,`et`.`LastUpdBy` AS `LastUpdBy`,`et`.`Date` AS `Date`,`et`.`EmployeeShiftID` AS `EmployeeShiftID`,`et`.`EmployeeID` AS `EmployeeID`,`et`.`EmployeeSalaryID` AS `EmployeeSalaryID`,`et`.`EmployeeFixedSalaryFlag` AS `EmployeeFixedSalaryFlag`,`et`.`RegularHoursWorked` AS `RegularHoursWorked`,`et`.`RegularHoursAmount` AS `RegularHoursAmount`,`et`.`TotalHoursWorked` AS `TotalHoursWorked`,`et`.`OvertimeHoursWorked` AS `OvertimeHoursWorked`,`et`.`OvertimeHoursAmount` AS `OvertimeHoursAmount`,`et`.`UndertimeHours` AS `UndertimeHours`,`et`.`UndertimeHoursAmount` AS `UndertimeHoursAmount`,`et`.`NightDifferentialHours` AS `NightDifferentialHours`,`et`.`NightDiffHoursAmount` AS `NightDiffHoursAmount`,`et`.`NightDifferentialOTHours` AS `NightDifferentialOTHours`,`et`.`NightDiffOTHoursAmount` AS `NightDiffOTHoursAmount`,`et`.`HoursLate` AS `HoursLate`,`et`.`HoursLateAmount` AS `HoursLateAmount`,`et`.`LateFlag` AS `LateFlag`,`et`.`PayRateID` AS `PayRateID`,`et`.`VacationLeaveHours` AS `VacationLeaveHours`,`et`.`SickLeaveHours` AS `SickLeaveHours`,`et`.`MaternityLeaveHours` AS `MaternityLeaveHours`,`et`.`OtherLeaveHours` AS `OtherLeaveHours`,`et`.`AdditionalVLHours` AS `AdditionalVLHours`,`et`.`TotalDayPay` AS `TotalDayPay`,`et`.`Absent` AS `Absent`,`et`.`TaxableDailyAllowance` AS `TaxableDailyAllowance`,`et`.`HolidayPayAmount` AS `HolidayPayAmount`,`et`.`TaxableDailyBonus` AS `TaxableDailyBonus`,`et`.`NonTaxableDailyBonus` AS `NonTaxableDailyBonus`,`et`.`IsValidForHolidayPayment` AS `IsValidForHolidayPayment`,`et`.`VacationLeaveHours` + `et`.`SickLeaveHours` + `et`.`MaternityLeaveHours` + `et`.`OtherLeaveHours` + `et`.`AdditionalVLHours` AS `LeaveHours`,`esa`.`DailyRate` / `sh`.`DivisorToDailyRate` * (`et`.`VacationLeaveHours` + `et`.`SickLeaveHours` + `et`.`MaternityLeaveHours` + `et`.`OtherLeaveHours` + `et`.`AdditionalVLHours`) AS `LeavePayment` from (((((`employeetimeentry` `et` join `employeeshift` `esh` on(`esh`.`EmployeeID` = `et`.`EmployeeID` and `esh`.`OrganizationID` = `et`.`OrganizationID` and `et`.`Date` between `esh`.`EffectiveFrom` and `esh`.`EffectiveTo`)) join `shift` `sh` on(`sh`.`RowID` = `esh`.`ShiftID`)) join `employee` `e` on(`e`.`RowID` = `et`.`EmployeeID` and `e`.`OrganizationID` = `et`.`OrganizationID` and find_in_set(`e`.`EmploymentStatus`,`UNEMPLOYEMENT_STATUSES`()) = 0)) join `organization` `og` on(`og`.`RowID` = `et`.`OrganizationID` and `og`.`NoPurpose` = 0)) join `employeesalary_withdailyrate` `esa` on(`esa`.`RowID` = `et`.`EmployeeSalaryID`)) where `et`.`VacationLeaveHours` + `et`.`SickLeaveHours` + `et`.`MaternityLeaveHours` + `et`.`OtherLeaveHours` + `et`.`AdditionalVLHours` > 0 group by `et`.`RowID` ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
