/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP VIEW IF EXISTS `paystubitem_sum_daily_allowance_group_prodid`;
DROP TABLE IF EXISTS `paystubitem_sum_daily_allowance_group_prodid`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `paystubitem_sum_daily_allowance_group_prodid` AS select `p`.`RowID` AS `ProductID`,`et`.`EmployeeID` AS `EmployeeID`,`et`.`OrganizationID` AS `OrganizationID`,`et`.`Date` AS `Date`,0 AS `Column1`,`esa`.`DailyRate` AS `Column2`,if(`pr`.`PayType` = 'Regular Day',round(if(`p`.`PartNo` = 'Ecola' and `et`.`TotalDayPay` > 0,`esa`.`DailyRate`,`et`.`RegularHoursAmount` * if((`es`.`RestDay` = '1' or `es`.`RestDay` is null) and `e`.`CalcRestDay` = '1',`pr`.`PayRate` / `pr`.`RestDayRate`,1) + `esa`.`DailyRate` / ifnull(`sh`.`DivisorToDailyRate`,8) * greatest(`et`.`VacationLeaveHours`,`et`.`SickLeaveHours`,`et`.`MaternityLeaveHours`,`et`.`OtherLeaveHours`)),2),if(`pr`.`PayType` = 'Special Non-Working Holiday' and `e`.`CalcSpecialHoliday` = '1',if(`e`.`EmployeeType` = 'Daily',`et`.`RegularHoursAmount` / `pr`.`PayRate`,`et`.`HolidayPayAmount`),if(`pr`.`PayType` = 'Special Non-Working Holiday' and `e`.`CalcSpecialHoliday` = '0',if(`e`.`EmployeeType` = 'Daily',`et`.`RegularHoursAmount`,`et`.`HolidayPayAmount`),if(`pr`.`PayType` = 'Regular Holiday' and `e`.`CalcHoliday` = '1',`et`.`HolidayPayAmount` + (`et`.`VacationLeaveHours` + `et`.`SickLeaveHours` + `et`.`MaternityLeaveHours` + `et`.`OtherLeaveHours`) * (`esa`.`DailyRate` / ifnull(`sh`.`DivisorToDailyRate`,0)),0)))) / `esa`.`DailyRate` * `ea`.`AllowanceAmount` AS `TotalAllowanceAmt` from (((((((`employeetimeentry` `et` join `employee` `e` on(`e`.`OrganizationID` = `et`.`OrganizationID` and `e`.`RowID` = `et`.`EmployeeID` and find_in_set(`e`.`EmploymentStatus`,`UNEMPLOYEMENT_STATUSES`()) = 0)) left join `employeeshift` `es` on(`es`.`RowID` = `et`.`EmployeeShiftID`)) left join `shift` `sh` on(`sh`.`RowID` = `es`.`ShiftID`)) join `employeeallowance` `ea` on(`ea`.`AllowanceFrequency` = 'Daily' and `ea`.`EmployeeID` = `e`.`RowID` and `ea`.`OrganizationID` = `e`.`OrganizationID` and `et`.`Date` between `ea`.`EffectiveStartDate` and `ea`.`EffectiveEndDate`)) join `product` `p` on(`p`.`RowID` = `ea`.`ProductID`)) join `payrate` `pr` on(`pr`.`RowID` = `et`.`PayRateID`)) join `employeesalary_withdailyrate` `esa` on(`esa`.`RowID` = `et`.`EmployeeSalaryID`)) ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
