/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP VIEW IF EXISTS `proper_payroll`;
DROP TABLE IF EXISTS `proper_payroll`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `proper_payroll` AS select `paystub`.`RowID` AS `RowID`,`paystub`.`OrganizationID` AS `OrganizationID`,`paystub`.`PayPeriodID` AS `PayPeriodID`,`paystub`.`EmployeeID` AS `EmployeeID`,`paystub`.`TimeEntryID` AS `TimeEntryID`,`paystub`.`PayFromDate` AS `PayFromDate`,`paystub`.`PayToDate` AS `PayToDate`,`paystub`.`TotalGrossSalary` AS `TotalGrossSalary`,`paystub`.`TotalNetSalary` AS `TotalNetSalary`,`paystub`.`TotalTaxableSalary` AS `TotalTaxableSalary`,`paystub`.`TotalEmpSSS` AS `TotalEmpSSS`,`paystub`.`TotalEmpWithholdingTax` AS `TotalEmpWithholdingTax`,`paystub`.`TotalCompSSS` AS `TotalCompSSS`,`paystub`.`TotalEmpPhilhealth` AS `TotalEmpPhilhealth`,`paystub`.`TotalCompPhilhealth` AS `TotalCompPhilhealth`,`paystub`.`TotalEmpHDMF` AS `TotalEmpHDMF`,`paystub`.`TotalCompHDMF` AS `TotalCompHDMF`,`paystub`.`TotalVacationDaysLeft` AS `TotalVacationDaysLeft`,`paystub`.`TotalLoans` AS `TotalLoans`,`paystub`.`TotalBonus` AS `TotalBonus`,`paystub`.`TotalAllowance` AS `TotalAllowance`,`paystub`.`TotalAdjustments` AS `TotalAdjustments`,`paystub`.`ThirteenthMonthInclusion` AS `ThirteenthMonthInclusion`,0 AS `AsActual` from `paystub` union select `paystubactual`.`RowID` AS `RowID`,`paystubactual`.`OrganizationID` AS `OrganizationID`,`paystubactual`.`PayPeriodID` AS `PayPeriodID`,`paystubactual`.`EmployeeID` AS `EmployeeID`,`paystubactual`.`TimeEntryID` AS `TimeEntryID`,`paystubactual`.`PayFromDate` AS `PayFromDate`,`paystubactual`.`PayToDate` AS `PayToDate`,`paystubactual`.`TotalGrossSalary` AS `TotalGrossSalary`,`paystubactual`.`TotalNetSalary` AS `TotalNetSalary`,`paystubactual`.`TotalTaxableSalary` AS `TotalTaxableSalary`,`paystubactual`.`TotalEmpSSS` AS `TotalEmpSSS`,`paystubactual`.`TotalEmpWithholdingTax` AS `TotalEmpWithholdingTax`,`paystubactual`.`TotalCompSSS` AS `TotalCompSSS`,`paystubactual`.`TotalEmpPhilhealth` AS `TotalEmpPhilhealth`,`paystubactual`.`TotalCompPhilhealth` AS `TotalCompPhilhealth`,`paystubactual`.`TotalEmpHDMF` AS `TotalEmpHDMF`,`paystubactual`.`TotalCompHDMF` AS `TotalCompHDMF`,`paystubactual`.`TotalVacationDaysLeft` AS `TotalVacationDaysLeft`,`paystubactual`.`TotalLoans` AS `TotalLoans`,`paystubactual`.`TotalBonus` AS `TotalBonus`,`paystubactual`.`TotalAllowance` AS `TotalAllowance`,`paystubactual`.`TotalAdjustments` AS `TotalAdjustments`,`paystubactual`.`ThirteenthMonthInclusion` AS `ThirteenthMonthInclusion`,1 AS `AsActual` from `paystubactual` ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
