/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP VIEW IF EXISTS `reportlist`;
DROP TABLE IF EXISTS `reportlist`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `reportlist` AS SELECT CONVERT('Attendance sheet' USING utf8) `ReportName`
UNION SELECT CONVERT('Alpha list' USING utf8)
UNION SELECT CONVERT('Employee\'s Employment Record' USING utf8)
UNION SELECT CONVERT('Employee\'s History of Salary Increase' USING utf8)
UNION SELECT CONVERT('Employee\'s Identification Number' USING utf8)
UNION SELECT CONVERT('Employee\'s Offenses' USING utf8)
UNION SELECT CONVERT('Employee\'s payroll Ledger' USING utf8)
UNION SELECT CONVERT('Employee 13th Month Pay Report' USING utf8)
# UNION SELECT CONVERT('Employee Leave Ledger' USING utf8)
UNION SELECT CONVERT('Filed Leaves Report' USING utf8)
UNION SELECT CONVERT('Employee Leave Balance Summary' USING utf8)
UNION SELECT CONVERT('Employee Loan Report' USING utf8)
UNION SELECT CONVERT('Employee Loan Summary Report' USING utf8)
UNION SELECT CONVERT('Employee Personal Information' USING utf8)
UNION SELECT CONVERT('PAGIBIG Monthly Report' USING utf8)
UNION SELECT CONVERT('Payroll Summary Report' USING utf8)
UNION SELECT CONVERT('PhilHealth Monthly Report' USING utf8)
UNION SELECT CONVERT('SSS Monthly Report' USING utf8)
UNION SELECT CONVERT('Tax Monthly Report' USING utf8)
UNION SELECT CONVERT('Post Employment Clearance' USING utf8)
UNION SELECT CONVERT('Agency Fee' USING utf8)
UNION SELECT CONVERT('Excessive Tardiness report' USING utf8) ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
