/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP VIEW IF EXISTS `tenhour`;
DROP TABLE IF EXISTS `tenhour`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `tenhour` AS SELECT 30 `MinuteInterval`
UNION SELECT 60
UNION SELECT 90
UNION SELECT 120
UNION SELECT 150
UNION SELECT 180
UNION SELECT 210
UNION SELECT 240
UNION SELECT 270
UNION SELECT 300
UNION SELECT 330
UNION SELECT 360
UNION SELECT 390
UNION SELECT 420
UNION SELECT 450
UNION SELECT 480
UNION SELECT 510
UNION SELECT 540
UNION SELECT 570
UNION SELECT 600 ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
