/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP FUNCTION IF EXISTS `UndertimeLog`;
DELIMITER //
CREATE FUNCTION `UndertimeLog`(`timeStamp1` TIMESTAMP,
	`timeStamp2` TIMESTAMP,
	`timeStamp3` TIMESTAMP

) RETURNS timestamp
    DETERMINISTIC
BEGIN

DECLARE returnValue TIMESTAMP;

SELECT MAX(i.TimeLog)
FROM (SELECT timeStamp1 `TimeLog`
	UNION
		SELECT timeStamp2 `TimeLog`
	UNION
		SELECT timeStamp3 `TimeLog`) i
WHERE i.`TimeLog` IS NOT NULL
INTO returnValue;

RETURN returnValue;

END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
