/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP PROCEDURE IF EXISTS `UpdatePredictedLoans`;
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `UpdatePredictedLoans`()
BEGIN

DECLARE i, orgCount INT(11) DEFAULT 0;
DECLARE orgID INT(11) DEFAULT 0;

SELECT COUNT(RowID) FROM organization INTO orgCount;

WHILE i < orgCount DO
	SELECT og.RowID
	FROM organization og
	ORDER BY og.RowID
	LIMIT i, 1
	INTO orgID;
	
#	SELECT CONC
	
	SET i = i + 1;
END WHILE;

END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
