/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP VIEW IF EXISTS `v_emptimeenetryholidaypay`;
DROP TABLE IF EXISTS `v_emptimeenetryholidaypay`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `v_emptimeenetryholidaypay` AS select `ete`.`RowID` AS `RowID`,`ete`.`OrganizationID` AS `OrganizationID`,`ete`.`Created` AS `Created`,`ete`.`CreatedBy` AS `CreatedBy`,`ete`.`LastUpd` AS `LastUpd`,`ete`.`LastUpdBy` AS `LastUpdBy`,`ete`.`Date` AS `Date`,`ete`.`EmployeeShiftID` AS `EmployeeShiftID`,`ete`.`EmployeeID` AS `EmployeeID`,`ete`.`EmployeeSalaryID` AS `EmployeeSalaryID`,`ete`.`EmployeeFixedSalaryFlag` AS `EmployeeFixedSalaryFlag`,`ete`.`RegularHoursWorked` AS `RegularHoursWorked`,`ete`.`RegularHoursAmount` AS `RegularHoursAmount`,`ete`.`TotalHoursWorked` AS `TotalHoursWorked`,`ete`.`OvertimeHoursWorked` AS `OvertimeHoursWorked`,`ete`.`OvertimeHoursAmount` AS `OvertimeHoursAmount`,`ete`.`UndertimeHours` AS `UndertimeHours`,`ete`.`UndertimeHoursAmount` AS `UndertimeHoursAmount`,`ete`.`NightDifferentialHours` AS `NightDifferentialHours`,`ete`.`NightDiffHoursAmount` AS `NightDiffHoursAmount`,`ete`.`NightDifferentialOTHours` AS `NightDifferentialOTHours`,`ete`.`NightDiffOTHoursAmount` AS `NightDiffOTHoursAmount`,`ete`.`HoursLate` AS `HoursLate`,`ete`.`HoursLateAmount` AS `HoursLateAmount`,`ete`.`LateFlag` AS `LateFlag`,`ete`.`PayRateID` AS `PayRateID`,`ete`.`VacationLeaveHours` AS `VacationLeaveHours`,`ete`.`SickLeaveHours` AS `SickLeaveHours`,`ete`.`MaternityLeaveHours` AS `MaternityLeaveHours`,`ete`.`OtherLeaveHours` AS `OtherLeaveHours`,`ete`.`AdditionalVLHours` AS `AdditionalVLHours`,`ete`.`TotalDayPay` AS `TotalDayPay`,`ete`.`Absent` AS `Absent`,`ete`.`TaxableDailyAllowance` AS `TaxableDailyAllowance`,`ete`.`HolidayPayAmount` AS `HolidayPayAmount`,`ete`.`TaxableDailyBonus` AS `TaxableDailyBonus`,`ete`.`NonTaxableDailyBonus` AS `NonTaxableDailyBonus`,`ete`.`IsValidForHolidayPayment` AS `IsValidForHolidayPayment`,`pr`.`PayType` AS `PayType`,`pr`.`PayRate` AS `PayRate`,`pr`.`OvertimeRate` AS `OvertimeRate`,`pr`.`NightDifferentialRate` AS `NightDifferentialRate`,`pr`.`NightDifferentialOTRate` AS `NightDifferentialOTRate`,`pr`.`RestDayRate` AS `RestDayRate`,`pr`.`RestDayOvertimeRate` AS `RestDayOvertimeRate`,`ete`.`TotalDayPay` - `ete`.`TotalDayPay` / `pr`.`PayRate` AS `HolidayPay` from (`employeetimeentry` `ete` join `payrate` `pr` on(`pr`.`OrganizationID` = `ete`.`OrganizationID` and `pr`.`Date` = `ete`.`Date`)) ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
