/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP VIEW IF EXISTS `v_employeesemimonthlyallowance`;
DROP TABLE IF EXISTS `v_employeesemimonthlyallowance`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `v_employeesemimonthlyallowance` AS select `ea`.`RowID` AS `RowID`,`ea`.`OrganizationID` AS `OrganizationID`,`ea`.`Created` AS `Created`,`ea`.`CreatedBy` AS `CreatedBy`,`ea`.`LastUpd` AS `LastUpd`,`ea`.`LastUpdBy` AS `LastUpdBy`,`ea`.`EmployeeID` AS `EmployeeID`,`ea`.`ProductID` AS `ProductID`,`ea`.`EffectiveStartDate` AS `EffectiveStartDate`,`ea`.`AllowanceFrequency` AS `AllowanceFrequency`,`ea`.`EffectiveEndDate` AS `EffectiveEndDate`,`ea`.`TaxableFlag` AS `TaxableFlag`,`ea`.`AllowanceAmount` AS `AllowanceAmount`,`ea`.`AllowanceAmount` / (`e`.`WorkDaysPerYear` / (12 * `PAYFREQUENCY_DIVISOR`(`pf`.`PayFrequencyType`))) AS `DailyAllowance`,0 AS `IsFixed` from (((`employeeallowance` `ea` join `employee` `e` on(`e`.`RowID` = `ea`.`EmployeeID` and `e`.`OrganizationID` = `ea`.`OrganizationID` and `e`.`EmployeeType` <> 'Daily' and `e`.`EmploymentStatus` not in ('Resigned','Terminated'))) join `payfrequency` `pf` on(`pf`.`RowID` = `e`.`PayFrequencyID`)) join `product` `p` on(`p`.`RowID` = `ea`.`ProductID` and `p`.`Fixed` = 0)) where `ea`.`AllowanceFrequency` = 'Semi-monthly' union select `ea`.`RowID` AS `RowID`,`ea`.`OrganizationID` AS `OrganizationID`,`ea`.`Created` AS `Created`,`ea`.`CreatedBy` AS `CreatedBy`,`ea`.`LastUpd` AS `LastUpd`,`ea`.`LastUpdBy` AS `LastUpdBy`,`ea`.`EmployeeID` AS `EmployeeID`,`ea`.`ProductID` AS `ProductID`,`ea`.`EffectiveStartDate` AS `EffectiveStartDate`,`ea`.`AllowanceFrequency` AS `AllowanceFrequency`,`ea`.`EffectiveEndDate` AS `EffectiveEndDate`,`ea`.`TaxableFlag` AS `TaxableFlag`,`ea`.`AllowanceAmount` AS `AllowanceAmount`,`ea`.`AllowanceAmount` / (`e`.`WorkDaysPerYear` / (12 * `PAYFREQUENCY_DIVISOR`(`pf`.`PayFrequencyType`))) AS `DailyAllowance`,1 AS `IsFixed` from (((`employeeallowance` `ea` join `employee` `e` on(`e`.`RowID` = `ea`.`EmployeeID` and `e`.`OrganizationID` = `ea`.`OrganizationID` and `e`.`EmployeeType` <> 'Daily' and `e`.`EmploymentStatus` not in ('Resigned','Terminated'))) join `payfrequency` `pf` on(`pf`.`RowID` = `e`.`PayFrequencyID`)) join `product` `p` on(`p`.`RowID` = `ea`.`ProductID` and `p`.`Fixed` = 1)) where `ea`.`AllowanceFrequency` = 'Semi-monthly' ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
