
Public Interface IEmployee
    Property RowID As Integer?
    Property CreatedBy As Integer?
    Property Created As DateTime
    Property LastUpdBy As Integer?
    Property LastUpd As DateTime
    Property OrganizationID As Integer?
    Property Salutation As String
    Property FirstName As String
    Property MiddleName As String
    Property LastName As String
    Property Surname As String
    Property EmployeeID As String
    Property TINNo As String
    Property SSSNo As String
    Property HDMFNo As String
    Property PhilHealthNo As String
    Property EmploymentStatus As String
    Property EmailAddress As String
    Property WorkPhone As String
    Property HomePhone As String
    Property MobilePhone As String
    Property HomeAddress As String
    Property Nickname As String
    Property JobTitle As String
    Property Gender As String
    Property EmployeeType As String
    Property MaritalStatus As String
    Property Birthdate As Date
    Property StartDate As Date
    Property TerminationDate As Date
    Property PositionID As Integer?
    Property PayFrequencyID As Integer?
    Property NoOfDependents As Integer?
    Property UndertimeOverride As String
    Property OvertimeOverride As String
    Property NewEmployeeFlag As String
    Property LeaveBalance As Decimal
    Property SickLeaveBalance As Decimal
    Property MaternityLeaveBalance As Decimal
    Property OtherLeaveBalance As Decimal
    Property LeaveAllowance As Decimal
    Property SickLeaveAllowance As Decimal
    Property MaternityLeaveAllowance As Decimal
    Property OtherLeaveAllowance As Decimal
    Property LeavePerPayPeriod As Decimal
    Property SickLeavePerPayPeriod As Decimal
    Property MaternityLeavePerPayPeriod As Decimal
    Property OtherLeavePerPayPeriod As Decimal
    Property AlphaListExempted As Char
    Property WorkDaysPerYear As Integer?
    Property DayOfRest As Char
    Property ATMNo As String
    Property BankName As String
    Property CalcHoliday As Char
    Property CalcSpecialHoliday As Char
    Property CalcNightDiff As Char
    Property CalcNightDiffOT As Char
    Property CalcRestDay As Char
    Property CalcRestDayOT As Char
    Property DateRegularized As Date
    Property DateEvaluated As Date
    Property RevealInPayroll As Char
    Property LateGracePeriod As Decimal
    Property AgencyID As Integer?
    Property OffsetBalance As Decimal
    Property DateR1A As Date
    Property AdditionalVLAllowance As Decimal
    Property AdditionalVLBalance As Decimal
    Property AdditionalVLPerPayPeriod As Decimal
    Property LeaveTenthYearService As Decimal
    Property LeaveFifteenthYearService As Decimal
    Property LeaveAboveFifteenthYearService As Decimal
    Property DeptManager As Integer?

End Interface